// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiDqA2M213E5qiugvfCj0UEQF8Aj8d7G0',
    appId: '1:460180747638:web:8504bf0ff94669a43d3657',
    messagingSenderId: '460180747638',
    projectId: 'flutter-notification-f1eea',
    authDomain: 'flutter-notification-f1eea.firebaseapp.com',
    storageBucket: 'flutter-notification-f1eea.firebasestorage.app',
    measurementId: 'G-PL14GNG8HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsK8BNXNSnNYGbNWrj70BbUX4AU-sg4U0',
    appId: '1:460180747638:android:9c100136d30710b33d3657',
    messagingSenderId: '460180747638',
    projectId: 'flutter-notification-f1eea',
    storageBucket: 'flutter-notification-f1eea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRCRZ5FFSHFwBsCk4YUxviy6s13nu0AI',
    appId: '1:460180747638:ios:2412748b3a178b023d3657',
    messagingSenderId: '460180747638',
    projectId: 'flutter-notification-f1eea',
    storageBucket: 'flutter-notification-f1eea.firebasestorage.app',
    iosBundleId: 'com.suppa.notificationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIRCRZ5FFSHFwBsCk4YUxviy6s13nu0AI',
    appId: '1:460180747638:ios:487ee04c1c8d9fc33d3657',
    messagingSenderId: '460180747638',
    projectId: 'flutter-notification-f1eea',
    storageBucket: 'flutter-notification-f1eea.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiDqA2M213E5qiugvfCj0UEQF8Aj8d7G0',
    appId: '1:460180747638:web:586a658bbe8dfda93d3657',
    messagingSenderId: '460180747638',
    projectId: 'flutter-notification-f1eea',
    authDomain: 'flutter-notification-f1eea.firebaseapp.com',
    storageBucket: 'flutter-notification-f1eea.firebasestorage.app',
    measurementId: 'G-P6E78FLC2D',
  );
}
